accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'), # User [C]reate
    path('login/', views.login, name='login'), # Session [C]reate
    path('logout/', views.logout, name='logout'), # Session [D]elete
    path('delete/', views.delete, name='delete'), # User [D]elete
    path('edit/', views.edit, name='edit'), # User [U]pdate
    path('password/', views.password, name='password'), # (Password) [U]pdate
    path('profile/', views.profile_detail, name='profile_detail'), # Profile [R]ead
    path('profile/edit/', views.profile_edit, name='profile_edit'), # Profile [U]pdate
    path('<str:username>/', views.profile, name='profile'),
]

monitor/urls.py
from django.urls import path
from . import views

app_name = "monitor"

urlpatterns = [
    path('', views.index, name="index"),
    path('noti/', views.notification, name='noti'),
    path('plant/<int:plant>', views.plant, name='plant'),
    path('plant/<int:plant>/loc/<int:loc>', views.loc, name='loc'),
    path('visualization/', views.visualization, name='visualization'),
    path('email/<int:plant>',views.sendMail, name='sendmail'),
]

raspberry/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.shortcuts import redirect

from fcm_django.api.rest_framework import FCMDeviceAuthorizedViewSet, FCMDeviceViewSet
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'devices', FCMDeviceViewSet)


urlpatterns = [
    path('admin/', admin.site.urls), #관리자
    path('monitor/', include('monitor.urls')), #메인
    path('accounts/', include('accounts.urls')), #로그인

    #path('plotly_django_tutorial/', include('plotly_django_tutorial.urls')),
    path('', lambda r: redirect("monitor/plant/1"), name='root'),

    url(r'^', include(router.urls))
]

monitor/models.py
from django.db import models
from django_pandas.managers import DataFrameManager


class PlantEnviron(models.Model):
    PLANT_CHOICE = [('1', '1'), ('2', '2')]
    plant         = models.CharField(max_length=1, choices=PLANT_CHOICE)
    recTime       = models.DateTimeField()
    tem_in_loc1	  = models.FloatField()
    hum_in_loc1	  = models.FloatField()
    tem_coil_loc1 = models.FloatField()
    tem_in_loc2	  = models.FloatField()
    hum_in_loc2	  = models.FloatField()
    tem_coil_loc2 = models.FloatField()	
    tem_in_loc3	  = models.FloatField()  
    hum_in_loc3	  = models.FloatField()  
    tem_coil_loc3 = models.FloatField()	    
    tem_out_loc1  = models.FloatField()	
    hum_out_loc1  = models.FloatField()   
    cond_loc1	  = models.BooleanField()
    cond_loc2	  = models.BooleanField()
    cond_loc3     = models.BooleanField()

    objects = DataFrameManager()


class WeatherForecast(models.Model):
    fcTime   = models.DateTimeField()
    temp_25	 = models.FloatField() 
    temp_46	 = models.FloatField()      
    humid_25 = models.FloatField()      	
    humid_46 = models.FloatField()      	
    rain_25	 = models.FloatField()      
    rain_46	 = models.FloatField()      
    wind_25	 = models.FloatField()      
    wind_46  = models.FloatField()   

    objects = DataFrameManager()


class Prediction(models.Model):
    PLANT_CHOICE = [('1', '1'), ('2', '2')]
    FORECAST_CHOICE = [('24', '24'), ('48', '48')]
    plant         = models.CharField(max_length=1, choices=PLANT_CHOICE)
    forecast      = models.CharField(max_length=2, choices=FORECAST_CHOICE)
    recTime       = models.DateTimeField()
    tem_in_loc1	  = models.FloatField()
    hum_in_loc1	  = models.FloatField()
    tem_coil_loc1 = models.FloatField()
    tem_in_loc2	  = models.FloatField()
    hum_in_loc2	  = models.FloatField()
    tem_coil_loc2 = models.FloatField()	
    tem_in_loc3	  = models.FloatField()  
    hum_in_loc3	  = models.FloatField()  
    tem_coil_loc3 = models.FloatField()	    
    tem_out_loc1  = models.FloatField()	
    hum_out_loc1  = models.FloatField()
    cond_loc1     = models.BooleanField()
    cond_loc2     = models.BooleanField()
    cond_loc3     = models.BooleanField()

    
    objects = DataFrameManager()

monitor/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django_pandas.managers import DataFrameManager
from fcm_django.models import FCMDevice
from django.db.models import F
from django.http import HttpResponseRedirect


from .models import PlantEnviron, WeatherForecast, Prediction

import re
import pandas as pd
import numpy as np
from datetime import timedelta
from plotly.offline import plot #plotly
from plotly.graph_objs import *
import plotly.graph_objs as go
from plotly.subplots import make_subplots



from django.core import mail
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.http import HttpResponse



@login_required
def index(request):
    context = {
        'plant':0
    }
    return render(request, 'monitor/index.html', context)


@login_required
def plant(request, plant):
    env = PlantEnviron.objects.order_by(F('recTime').desc()).filter(plant=plant).first()
    pred24 = Prediction.objects.order_by(F('recTime').desc()).filter(plant=plant).filter(forecast='24')[:24]
    pred48 = Prediction.objects.order_by(F('recTime').desc()).filter(plant=plant).filter(forecast='48')[:24]
    cond24 = pred24.to_dataframe()
    cond24 = cond24.filter(regex='cond').apply(lambda x: any(x))
    cond48 = pred48.to_dataframe()
    cond48 = cond48.filter(regex='cond').apply(lambda x: any(x))

    context = {
        'plant': plant,
        'env': env,
        'pred24': pred24,
        'pred48': pred48,
        'cond24': cond24,
        'cond48': cond48,
    }


    return render(request, 'monitor/plant.html', context)


@login_required
def loc(request, plant, loc):

    # 현재 공장 환경 (차트)
    # 공장 환경 : 현재 값-24시간 + 현재 기준으로 24, 48예측 값 (plotly)
    env = PlantEnviron.objects.order_by(F('recTime').desc()).filter(plant=plant)[:24]
    pred24 = Prediction.objects.order_by(F('recTime').desc()).filter(plant=plant).filter(forecast='24')[:24]
    pred48 = Prediction.objects.order_by(F('recTime').desc()).filter(plant=plant).filter(forecast='48')[:24]



    env_df = env.to_dataframe().sort_values(by=['recTime'])
    pred24_df = pred24.to_dataframe().sort_values(by=['recTime'])
    pred24_df['recTime'] = pred24_df['recTime'] + pd.offsets.Hour(24)
    pred48_df = pred48.to_dataframe().sort_values(by=['recTime'])
    pred48_df['recTime'] = pred48_df['recTime'] + pd.offsets.Hour(48)

    #(마지막 line그래프에서 써야함)

    # #loc 선택
    filters = f'((in|coil|cond)_loc{loc}|out|recTime)'
    env_df = env_df.filter(regex=filters)
    pred24_df = pred24_df.filter(regex=filters)
    pred48_df = pred48_df.filter(regex=filters)
    env_df.columns = [re.sub('\d', '', col) for col in env_df.columns]
    pred24_df.columns = [re.sub('\d', '', col) for col in pred24_df.columns]
    pred48_df.columns = [re.sub('\d', '', col) for col in pred48_df.columns]

    cond24 = pred24_df.filter(regex='cond').apply(lambda x: any(x))
    cond48 = pred48_df.filter(regex='cond').apply(lambda x: any(x))
    #이슬점
    def dewpoint(temp, humid):
        return ((243.12 *((17.62 * temp /(243.12 + temp)) + np.log(humid / 100.0))) 
            / (17.62-((17.62 * temp / (243.12 + temp)) + np.log(humid/ 100.0))))

    tem_col = env_df.filter(regex='tem_in_').columns
    hum_col = env_df.filter(regex='hum_in_').columns

    dew_col = f'{tem_col[0][:3]}_dewpoint_{tem_col[0][-6:]}'
    print(dew_col)
    env_df[dew_col] = dewpoint(env_df[tem_col[0]], env_df[hum_col[0]])
    pred24_df[dew_col] = dewpoint(pred24_df[tem_col[0]], pred24_df[hum_col[0]])
    pred48_df[dew_col] = dewpoint(pred48_df[tem_col[0]], pred48_df[hum_col[0]])

    # #시각화
    #이중축있는 subplot
    fig = make_subplots(specs=[[{"secondary_y": True}]])    

    fig.add_trace(go.Scatter(x=env_df['recTime'], y=env_df['tem_in_loc'],  mode='lines+markers', name='온도',
                             opacity=0.8, marker_color='red'), secondary_y = False)
    fig.add_trace(go.Scatter(x=pred24_df['recTime'], y=pred24_df['tem_in_loc'], mode='lines+markers', name='24시간후 온도',
                             opacity=0.8, line = dict(color='red', width=3, dash='dash')), secondary_y = False)
    fig.add_trace(go.Scatter(x=pred48_df['recTime'], y=pred48_df['tem_in_loc'], mode='lines+markers', name='48시간후 온도',
                             opacity=0.8,line = dict(color='red', width=3, dash='dot')), secondary_y = False)

    fig.add_trace(go.Scatter(x=env_df['recTime'], y=env_df['tem_coil_loc'], mode='lines+markers',  name='코일온도',
                             opacity=0.8, marker_color='rgb(245,73,19)'), secondary_y = False)
    fig.add_trace(go.Scatter(x=pred24_df['recTime'], y=pred24_df['tem_coil_loc'], mode='lines+markers', name='24시간후 코일온도',
                             opacity=0.8, line = dict(color='rgb(245,73,19)', width=3, dash='dash')), secondary_y = False)
    fig.add_trace(go.Scatter(x=pred48_df['recTime'], y=pred48_df['tem_coil_loc'], mode='lines+markers', name='48시간후 코일온도',
                             opacity=0.8, line = dict(color='rgb(245,73,19)', width=3, dash='dot')), secondary_y = False)

    fig.add_trace(go.Scatter(x=env_df['recTime'], y=env_df['tem_dewpoint_in_loc'], mode='lines+markers',  name='이슬점',
                             opacity=0.8, marker_color='rgb(48,85,152)'), secondary_y = False)
    fig.add_trace(go.Scatter(x=pred24_df['recTime'], y=pred24_df['tem_dewpoint_in_loc'], mode='lines+markers', name='24시간후 이슬점',
                             opacity=0.8,  line = dict(color='rgb(48,85,152)', width=3, dash='dash')), secondary_y = False)
    fig.add_trace(go.Scatter(x=pred48_df['recTime'], y=pred48_df['tem_dewpoint_in_loc'], mode='lines+markers', name='48시간후 이슬점',
                             opacity=0.8, line = dict(color='rgb(48,85,152)', width=3, dash='dot')), secondary_y = False)

    fig.add_trace(go.Bar(x=env_df['recTime'], y=env_df['hum_in_loc'],  name='습도',
                             opacity=0.8, marker_color='skyblue'), secondary_y = True)
    fig.add_trace(go.Bar(x=pred24_df['recTime'], y=pred24_df['hum_in_loc'],  name='24시간후 습도',
                             opacity=0.8, marker_color='skyblue'), secondary_y = True)
    fig.add_trace(go.Bar(x=pred48_df['recTime'], y=pred48_df['hum_in_loc'],  name='48시간후 습도',
                             opacity=0.8, marker_color='skyblue'), secondary_y = True)
    

    fig.update_layout(title='<b>Today Factory Environment</b>',barmode='overlay', yaxis2=dict(showgrid=False, zeroline=False))
    fig.update_traces(yaxis='y2', selector={'type':'bar'}, marker_color='rgb(158,202,225)', marker_line_color='rgb(8,48,107)',
                  marker_line_width=1.0, opacity=0.5)
    fig.update_xaxes(title_text='<b>날짜</b>')
    fig.update_yaxes(title_text='<b>[ 온도(ºC) ]</b>')
    fig.update_yaxes(title_text='<b>[ 상대습도(%) ]</b>', secondary_y=True)

    plot_div = plot(fig, output_type='div')

    # TODO : 현재 ~ 24시간까지 결로 여부, 24~48시간 이내 결로 여부

    context = {
        'plant': plant,
        'loc': loc,
        'plant_envs': env_df.iloc[-1], #환경 CHART
        'plot_div': plot_div,
        'pred24': pred24_df.iloc[-1],
        'pred48': pred48_df.iloc[-1],
        'cond24': cond24,
        'cond48': cond48,
    }
    return render(request, 'monitor/loc.html', context)



def visualization(request):

    #현재값 + 예측값
    #plant_envs = Prediction.objects.all().order_by('recTime').last()
    plant_all = Prediction.objects.all()
    cnt = len(plant_all)-1
    plant_envs = plant_all[cnt] 
   
    # 공장 환경 : 현재 값-24시간 + 현재 기준으로 24, 48예측 값
 
    env_df = PlantEnviron.objects.all().filter(plant=plant).to_dataframe() 
    y_data = env_df.iloc[-24:, 1:]
    x_data = env_df.iloc[-24:, 1] #시간

    print(x_data)
    print(y_data)

    filters= f'(tem|hum)' + '_(in|coil)' + '_loc' + str(loc)
    y_data = y_data.filter(regex=filters, axis=1) # loc1? temp_in_loc1, hum_in_loc1, coil_in_loc1

    #24, 48시간 예측값
    objects = DataFrameManager()
    pred = Prediction.objects.all().to_dataframe()
    # print(pred)
    pred = pred.iloc[-48:,:] # 현재 관측값 기준 -24Hours
    # embed()
    if (pred['forecast'] == '24').bool:
        pred_24 = pred[pred['forecast'] == '24'] #24시간후 예측값 df
        pred_24 = pred_24.filter(regex=filters, axis=1)
    elif (pred['forecast'] == '48').bool:
        pred_48 = pred[pred['forecast'] == '48'] #48시간후 예측값 df
        pred_48 = pred_48.filter(regex=filters, axis=1)

    index_24 = pd.date_range(start=pred_24.index[-1], periods=24, freq='1H')
    # index_48 = pd.date_range(start=pred_48.index[-1], periods=48, freq='1H')

    plant_24 = pd.DataFrame({'index':index_24}).join(pred_24)
    # plant_48 = pd.DataFrame({'index':index_48}).join(pred_48)

    #시각화
    fig = go.Figure()

    fig.add_trace(go.Scatter(x=x_data.index, y=y_data.iloc[:,0], mode='lines+markers', name='온도',
                             opacity=0.8, marker_color='red'))

    fig.add_trace(go.Scatter(x=plant_24.index, y=plant_24.iloc[:,0], mode='lines+markers', name='24시간후 온도',
                             opacity=0.8, marker_color='green'))

    # fig.add_trace(go.Scatter(x=plant_48.index, y=plant_48.iloc[:,0], mode='lines+markers', name='48시간후 온도',
    #                          opacity=0.8, marker_color='orange'))
    fig.update_layout(title='<b>Today Factory Environment</b>', xaxis_title='Date', yaxis_title='Scale')

    plot_div = plot(fig, output_type='div')

    context = {
            'plant': plant,
            'loc': loc,
            'plant_envs' : plant_envs,
            'plot_div': plot_div,
            'x' : x_data,
            'y' : y_data,
        }

    return render(request, 'monitor/visualization.html', context)


def notification(request):
    device = FCMDevice.objects.all().first()
    device.send_message("title", "this is test message")
    context = {
        'plant': 0
    }

    return render(request, 'monitor/index.html', context)

@login_required
def sendMail(request, plant):

monitor/templates/monitor/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body %}

    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'monitor:plant' 1 %}">Don't Rust</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTop" aria-controls="navbarTop" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-md-center" id="navbarTop">
                <ul class="navbar-nav nav-pills mx-md-3">
                    <li class="nav-item text-nowrap">
                        <a class="nav-link {% if plant == 1 %}active{% endif %}" href="{% url 'monitor:plant' 1 %}">Plant1</a>
                    </li>
                    <li class="nav-item text-nowrap">
                        <a class="nav-link {% if plant == 2 %}active{% endif %}" href="{% url 'monitor:plant' 2 %}">Plant2</a>
                    </li>
                </ul>
                <ul class="navbar-nav nav-pills mx-md-3">
                    <li class="nav-item text-nowrap">
                        <a class="nav-link {% if plant == 0 %}disabled{% endif %}{% if loc == 1 %}active{% endif %}" href="{% url 'monitor:loc' plant 1 %}">LOC1</a>
                    </li>
                    <li class="nav-item text-nowrap">
                        <a class="nav-link {% if plant == 0 %}disabled{% endif %}{% if loc == 2 %}active{% endif %}" href="{% url 'monitor:loc' plant 2 %}">LOC2</a>
                    </li>
                    <li class="nav-item text-nowrap">
                        <a class="nav-link {% if plant == 0 %}disabled{% endif %}{% if loc == 3 %}active{% endif %}" href="{% url 'monitor:loc' plant 3 %}">LOC3</a>
                    </li>
                </ul>
                <form class="navbar-nav ml-auto" action="{% url 'accounts:logout' %}" method="POST">
                    {% csrf_token %}
                    <button class="btn btn-dark" type="submit">Sign out</button>
                </form>
            </div>

        </div>
    </nav>

    {% block plant %}

    {% endblock %}


    <script src="https://www.gstatic.com/firebasejs/7.15.5/firebase-app.js"></script>
    <script src="https://www.gstatic.com/firebasejs/7.15.5/firebase-messaging.js"></script>

    <script>
        // Your web app's Firebase configuration
        const firebaseConfig = {
            apiKey: "AIzaSyD6U2mC234IYhqRzwbaZWY_da_GMXLeiUc",
            authDomain: "django-fcm-test-5b82c.firebaseapp.com",
            databaseURL: "https://django-fcm-test-5b82c.firebaseio.com",
            projectId: "django-fcm-test-5b82c",
            storageBucket: "django-fcm-test-5b82c.appspot.com",
            messagingSenderId: "405299081661",
            appId: "1:405299081661:web:70371989391aa8249de2d4",
            measurementId: "G-8PQD6CE540"
        };

        // Initialize Firebase
        firebase.initializeApp(firebaseConfig);
        navigator.serviceWorker.register("{% static 'firebase-messaging-sw.js' %}")
            .then((registration) => {
                const messaging = firebase.messaging();
                messaging.useServiceWorker(registration);
                messaging.getToken().then((currentToken) => {
                    if (currentToken) {
                        sendTokenToServer(currentToken)
                    } else {
                        // Show permission request.
                        console.log('No Instance ID token available. Request permission to generate one.');

                    }
                }).catch((err) => {
                    console.log('An error occurred while retrieving token. ', err);
                });
            })

        function sendTokenToServer(currentToken) {
            fetch('http://localhost:8000/devices/', {
                method: "POST",
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({
                    'registration_id': currentToken,
                    'type': 'web',
                }),
                credentials: "include",
            }).then(function(response) {
                console.log(response);
            })
        }
    </script>
{% endblock body %}

monitor/templates/monitor/loc.html
{% extends 'monitor/index.html' %}


{% block plant %}
<!-- 차트 -->

<div class="container-fluid">
<table class="table table-bordered">
    <thead class="thead-light">
      <tr>
        <th scope="col">시간</th>
        <th scope="col">온도</th>
        <th scope="col">습도</th>
        <th scope="col">코일 온도</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>{{ plant_envs.recTime|date:'Y.m.d. H:00' }}</td>
        <td>{{ plant_envs.tem_in_loc|floatformat:2 }}</td>
        <td>{{ plant_envs.hum_in_loc|floatformat:2 }}</td>
        <td>{{ plant_envs.tem_coil_loc|floatformat:2 }}</td>
      </tr>
    </tbody>
  </table>
</div>

 <!-- 결로 차트 -->
<div class="container">
  <div class='table2base'>
    <table class="table table-bordered">
      <thead class="thead-light">
        <tr>
          <th scope="col">     </th>
          <th scope="col">24시간 이내</th>
          <th scope="col">48시간 이내</th>
        </tr>
      </thead>

      <tbody>
        <tr>
          <th scope="row">결로 여부</th>
          <td class="{{ cond24.cond_loc|yesno:"table-danger,," }}">{{ cond24.cond_loc|yesno:"YES, NO, ERR" }}</td>
          <td class="{{ cond48.cond_loc|yesno:"table-danger,," }}">{{ cond48.cond_loc|yesno:"YES, NO, ERR" }}</td>
        </tr>
      </tbody>
    </table>
  </div>
</div>


<!-- 라인 그래프 -->
<div class='container-fluid mt-5'>
  {{ plot_div|safe }}
  <div>
      {{ x_data }}
      {{ y_data }}
  </div>
</div>

{% endblock %}

monitor/templates/monitor/plant.html
{% extends 'monitor/index.html' %}

{% block plant %}

    <div class="container-fluid">
        <div class="row">
            <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar">
                <div class="sidebar-sticky pt-3">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link active" href="#">
                                <span data-feather="home"></span>
                                Dashboard <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="file"></span>
                                Orders
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="shopping-cart"></span>
                                Products
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="users"></span>
                                Customers
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="bar-chart-2"></span>
                                Reports
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="layers"></span>
                                Integrations
                            </a>
                        </li>
                    </ul>

                    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                        <span>Send reports</span>

                    </h6>
                    <ul class="nav flex-column mb-2">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'monitor:sendmail' plant %}?plant={{ plant }}">
                                <span data-feather="file-text"></span>
                                Current
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="file-text"></span>
                                Last quarter
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="file-text"></span>
                                Social engagement
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="file-text"></span>
                                Year-end sale
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>

            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
                <div class="d-flex justify-content-center flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 h2">
                    <div class="col-4">{{ env.recTime|date:'시간 : Y.m.d. H:00' }}</div>
                </div>
                <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
                    <table class="table table-bordered text-center">
                        <thead class="thead-light">
                        <tr>
                            <th scope="col">Location</th>
                            <th scope="col">현재 결로상태</th>
                            <th scope="col">24시간 결로여부</th>
                            <th scope="col">48시간 결로여부</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <th scope="row">LOC1</th>
                            <td class="{{ env.cond_loc1|yesno:"table-danger,," }}">{{ env.cond_loc1|yesno:"YES, NO, ERR" }}</td>
                            <td class="{{ cond24.cond_loc1|yesno:"table-danger,," }}">{{ cond24.cond_loc1|yesno:"YES, NO, ERR" }}</td>
                            <td class="{{ cond48.cond_loc1|yesno:"table-danger,," }}">{{ cond48.cond_loc1|yesno:"YES, NO, ERR" }}</td>
                        </tr>
                        <tr>
                            <th scope="row">LOC2</th>
                            <td class="{{ env.cond_loc2|yesno:"table-danger,," }}">{{ env.cond_loc2|yesno:"YES, NO, ERR" }}</td>
                            <td class="{{ cond24.cond_loc2|yesno:"table-danger,," }}">{{ cond24.cond_loc2|yesno:"YES, NO, ERR" }}</td>
                            <td class="{{ cond48.cond_loc2|yesno:"table-danger,," }}">{{ cond48.cond_loc2|yesno:"YES, NO, ERR" }}</td>
                        </tr>
                        <tr>
                            <th scope="row">LOC3</th>
                            <td class="{{ env.cond_loc3|yesno:"table-danger,," }}">{{ env.cond_loc3|yesno:"YES, NO, ERR" }}</td>
                            <td class="{{ cond24.cond_loc3|yesno:"table-danger,," }}">{{ cond24.cond_loc3|yesno:"YES, NO, ERR" }}</td>
                            <td class="{{ cond48.cond_loc3|yesno:"table-danger,," }}">{{ cond48.cond_loc3|yesno:"YES, NO, ERR" }}</td>
                        </tr>
                        </tbody>
                    </table>

                </div>
                <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                    <table class="table table-bordered text-center">
                        <thead class="thead-light">
                        <tr>
                            <th scope="col">Location</th>
                            <th scope="col">온도</th>
                            <th scope="col">습도</th>
                            <th scope="col">코일온도</th>
                            <th scope="col">외부온도</th>
                            <th scope="col">외부습도</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <th scope="row">LOC1</th>
                            <td>{{ env.tem_in_loc1|floatformat:2 }}</td>
                            <td>{{ env.hum_in_loc1|floatformat:2 }}</td>
                            <td>{{ env.tem_coil_loc1|floatformat:2 }}</td>
                            <td>{{ env.tem_out_loc1|floatformat:2 }}</td>
                            <td>{{ env.hum_out_loc1|floatformat:2 }}</td>
                        </tr>
                        <tr>
                            <th scope="row">LOC2</th>
                            <td>{{ env.tem_in_loc2|floatformat:2 }}</td>
                            <td>{{ env.hum_in_loc2|floatformat:2 }}</td>
                            <td>{{ env.tem_coil_loc2|floatformat:2 }}</td>
                            <td>{{ env.tem_out_loc1|floatformat:2 }}</td>
                            <td>{{ env.hum_out_loc1|floatformat:2 }}</td>
                        </tr>
                        <tr>
                            <th scope="row">LOC3</th>
                            <td>{{ env.tem_in_loc3|floatformat:2 }}</td>
                            <td>{{ env.hum_in_loc3|floatformat:2 }}</td>
                            <td>{{ env.tem_coil_loc3|floatformat:2 }}</td>
                            <td>{{ env.tem_out_loc1|floatformat:2 }}</td>
                            <td>{{ env.hum_out_loc1|floatformat:2 }}</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </main>
        </div>
    </div>


{% endblock %}